spring.datasource.url=jdbc:mysql://localhost:3306/dividend_lab?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=dividend_app
spring.datasource.password=devlop
